const products = [
    {
      id: 1,
      name: "Product 1",
      price: 29.99,
      image: "https://via.placeholder.com/150",
      details: "Detailed description of Product 1",
      claspType: "Lobster Clasp",
      materialType: "terracotta",
      metalType: "No Metal Type",
      gemType: "No Gemstone",
      occasionType: "Wedding, Birthday",
      countryOfOrigin: "India",
      about:
        "Handmade - terracotta jewelries are handmade and no machines are used in the whole process. Colour Difference - The colour of the actual product can be different from what you see in the images.",
    },
    {
      id: 2,
      name: "Product 2",
      price: 49.99,
      image: "https://via.placeholder.com/150",
      details: "Detailed description of Product 2",
      claspType: "Lobster Clasp",
      materialType: "terracotta",
      metalType: "No Metal Type",
      gemType: "No Gemstone",
      occasionType: "Wedding, Birthday",
      countryOfOrigin: "India",
      about:
        "Handmade - terracotta jewelries are handmade and no machines are used in the whole process. Colour Difference - The colour of the actual product can be different from what you see in the images.",
    },
    {
      id: 3,
      name: "Product 3",
      price: 19.99,
      image: "https://via.placeholder.com/150",
      details: "Detailed description of Product 3",
      claspType: "Lobster Clasp",
      materialType: "terracotta",
      metalType: "No Metal Type",
      gemType: "No Gemstone",
      occasionType: "Wedding, Birthday",
      countryOfOrigin: "India",
      about:
        "Handmade - terracotta jewelries are handmade and no machines are used in the whole process. Colour Difference - The colour of the actual product can be different from what you see in the images.",
    },
    {
      id: 4,
      name: "Product 4",
      price: 99.99,
      image: "https://via.placeholder.com/150",
      details: "Detailed description of Product 4",
      claspType: "Lobster Clasp",
      materialType: "jute",
      metalType: "No Metal Type",
      gemType: "No Gemstone",
      occasionType: "Wedding, Birthday",
      countryOfOrigin: "India",
      about:
        "Handmade - jute jewelries are handmade and no machines are used in the whole process. Colour Difference - The colour of the actual product can be different from what you see in the images.",
    },
    {
      id: 5,
      name: "Product 5",
      price: 99.99,
      image: "https://via.placeholder.com/150",
      details: "Detailed description of Product 4",
      claspType: "Lobster Clasp",
      materialType: "terracotta",
      metalType: "No Metal Type",
      gemType: "No Gemstone",
      occasionType: "Wedding, Birthday",
      countryOfOrigin: "India",
      about:
        "Handmade - terracotta jewelries are handmade and no machines are used in the whole process. Colour Difference - The colour of the actual product can be different from what you see in the images.",
    },
    {
      id: 6,
      name: "Product 6",
      price: 99.99,
      image: "https://via.placeholder.com/150",
      details: "Detailed description of Product 4",
      claspType: "Lobster Clasp",
      materialType: "terracotta",
      metalType: "No Metal Type",
      gemType: "No Gemstone",
      occasionType: "Wedding, Birthday",
      countryOfOrigin: "India",
      about:
        "Handmade - terracotta jewelries are handmade and no machines are used in the whole process. Colour Difference - The colour of the actual product can be different from what you see in the images.",
    },
  ];

export default products;